export const Connita = {
    nom: 'Connita',
    description: "Une plateforme interactive où vous pouvez apprendre de nouvelles langues, découvrir des cultures fascinantes, et explorer des pays du monde entier. Ici, vous avez l'occasion de rencontrer des amis partageant les mêmes intérêts, de discuter avec eux en temps réel, et de créer des liens durables tout en pratiquant ensemble. Vous pouvez également publier des photos de vos voyages, de vos découvertes culturelles et vous laisser inspirer par les expériences des autres. Que vous cherchiez à enrichir vos connaissances ou à élargir votre cercle d'amis, cette plateforme vous ouvre la porte à un monde plus connecté et passionnant.",
    technologieUtiliser: ['html', 'css', 'javascript', 'vue.js', 'spring', 'jdbc', 'sql', 'gsap', 'ajax'],
    difficultes: "La principale difficulté que j'ai rencontrée est la grande taille du projet, qui a engendré une complexité considérable à gérer. La coordination de multiples fonctionnalités, l'intégration de technologies variées et la gestion des dépendances entre les différentes parties du projet ont demandé une planification rigoureuse et une attention constante aux détails. Cette échelle a également impliqué de nombreux défis en termes de maintenabilité et d'organisation du code, rendant le projet plus exigeant à chaque étape de son développement.",
    ceQueJAiAppris: "Ce projet m'a permis d'apprendre énormément, tant sur le plan technique qu'organisationnel. J'ai renforcé mes compétences en gestion de projets complexes, en apprenant à structurer efficacement mon code et à mieux organiser les différentes phases du développement. J'ai également acquis une meilleure maîtrise des technologies utilisées et développé une approche plus stratégique face aux défis, notamment en termes de planification et de résolution de problèmes. Cette expérience m'a surtout appris l'importance de la persévérance et de l'adaptabilité face à des projets de grande envergure.",
    gitRepoUrl: 'https://github.com/JamilFayad-1/Connita-Full-Stack',
    siteLiveUrl: 'null',
};

export const Wonders = {
    nom: 'Wonders of the world',
    description: "Une plateforme interactive où vous pouvez apprendre de nouvelles langues, découvrir des cultures fascinantes, et explorer des pays du monde entier. Ici, vous avez l'occasion de rencontrer des amis partageant les mêmes intérêts, de discuter avec eux en temps réel, et de créer des liens durables tout en pratiquant ensemble. Vous pouvez également publier des photos de vos voyages, de vos découvertes culturelles et vous laisser inspirer par les expériences des autres. Que vous cherchiez à enrichir vos connaissances ou à élargir votre cercle d'amis, cette plateforme vous ouvre la porte à un monde plus connecté et passionnant.",
    technologieUtiliser: ['html', 'css', 'javascript', 'spring', 'jdbc', 'sql', 'gsap', 'ajax'],
    difficultes: "Le concept de cette plateforme était de créer un site web hautement interactif et accessible à tous, peu importe leur niveau d'expérience avec les technologies. L’objectif principal était d’offrir une expérience utilisateur fluide, agréable et intuitive. Cependant, l'un des défis majeurs résidait dans la complexité des animations, qui devaient non seulement être visuellement captivantes mais aussi fonctionner de manière harmonieuse sur différents appareils et navigateurs. Intégrer ces animations tout en maintenant des performances optimales a demandé une réflexion approfondie et une maîtrise technique importante, rendant cette partie du projet particulièrement exigeante.",
    ceQueJAiAppris: "Grâce à ce projet, j'ai appris à perfectionner mes compétences en création d'interfaces utilisateur interactives. J'ai acquis une meilleure compréhension de la gestion des animations complexes et de leur impact sur la performance du site. Cela m'a également permis de développer une approche plus efficace pour optimiser le rendu des animations, tout en maintenant un équilibre entre esthétique et fluidité.",
    gitRepoUrl: 'null',
    siteLiveUrl: 'null',
};